Release/0.4.0
ONSdigital/dp-areas-api pull request #19
Opened 2021-03-10 14:27 UTC by HeJones

### What

- Added script to import region area data into Mongodb, and update script to upsert from insert

### How to review

- Check only changes to the script have been included

### Who can review

- Anyone

2021-03-10 14:54 UTC, daiLlew requested changes
Are there any unit tests that could be added to compliment the new functionality you've added?

2021-03-11 09:37 UTC, HeJones commented on import-areas/import-areas.go
> +		if err != nil {
I have reordered the variable declaration

2021-03-11 09:38 UTC, HeJones commented on import-areas/import-areas.go
> +		parentType, _ := lookupAreaType(binding.ParentCode.Value)
Thank you for spotting this

2021-03-11 09:39 UTC, HeJones commented on import-areas/import-areas.go
> +		if err != nil {
thank you for spotting this

2021-03-11 11:18 UTC, HeJones commented on import-areas/import-areas.go
> +	resp, _ := client.Do(req)
Thank you for spotting this, I have also handled the error on line 229 and for the similar queries in the function above

2021-03-11 11:18 UTC, HeJones commented on import-areas/import-areas.go
> +	data, _ := ioutil.ReadAll(resp.Body)
I am know handling this error

2021-03-15 11:59 UTC, HeJones commented
As this is a script for the moment I have not added any unit tests

2021-03-16 13:30 UTC, daiLlew approved these changes

2021-03-16 13:42 UTC, merged